### ISSUE TITLE
'find_docker_cmd' is not exported by automagic

### ISSUE THREAD

**Issue by bkkkk** [cole-brokamp/rize#1]
I'm don't know if this was intentional but in shiny_dockerize you are using find_docker_cmd from the automagic package but this function is not exported by it. I know rize has this function, I redefined this function in my global environment and removed automagic:: and it worked.

**Comment by cole-brokamp** [comment]
thanks for pointing this out @bkkkk. I believe that I have fixed this issue as of 68f43b57b809f30f10b3e5c0ec54f363cbe1ab2c. let me know if it works for you now.
