### ISSUE TITLE
Support for packrat

### ISSUE THREAD

**Issue by adamrobinson361** [cole-brokamp/rize#2]
Hi - can you let me know if your package has support for packrat?

Kind Regards,

Adam

**Comment by cole-brokamp** [comment]
No.  In my experience packrat is extremely bulky and doesn't always work well.  `rize` depends on the [`automagic`](https://github.com/cole-brokamp/automagic) package which currently handles github and CRAN dependencies.  Extra software dependencies can be installed manually or by using something like [shinyapps-package-dependencies](https://github.com/rstudio/shinyapps-package-dependencies). Pull requests always welcome though 😃

**Comment by adamrobinson361** [comment]
Ah that's interesting. I've only just started using packrat. Could you expand on the doesn't always work well point. Do you mean on the server side on in development. How do you go back to your app in say rstudio a year later and run your app with automagic? Wont all your packages be more up to date?

**Comment by cole-brokamp** [comment]
If I develop an app and then want to go back and edit it, I always work within a Docker container.  If you want to work locally, you can setup a local temporary library with devtools and use automagic to install version specific packages there.

I've had problems with Packrat in development before and also heard similar experiences from other users and even RStudio employees,
