### ISSUE TITLE
headless generation arguments

### ISSUE THREAD

**Issue by vsoch** [cole-brokamp/rize#6]
hey @cole-brokamp ! To make this work in a headless environment, we need another argument to shiny_dockerize to *not* automatically open / run the container and serve the application on a port. It could be possible to hack together calls to the other functions, but it feels cleaner to be able to do something like:

```R
shiny_dockerize(directory=getwd(), app.name="myshinyapp", run=FALSE)
```
It also might make sense to expose any of the other hard coded variables in the Dockerfile (and I think the PR that allows for Dockerfile templates might be relevant here?)

What are your thoughts? Also with the above, we should have a clean list of arguments for the user to provide to the function. I can map these variables in a CI setup.

**Comment by cole-brokamp** [comment]
i've merged this in from your PR and also have defaulted this to FALSE, thanks!
